version: 1
profile:
    email: 0braindrain@gmail.com
    accountId: 712020:0b830d12-44dc-42ba-b9b6-5857a20c313c
    auth_type: api_token
    token: !!binary |
        Q9KdKSqj1+NSUuXpeKIpJOAyib0zwpkXGaYa+F1MRTE6Ojo5NzEwMGM1ZTY5OTkxYTU0NG
        Y3ZmY3MmE5Y2U4MDM3OTg5YThlMWM4Nzc0NGU4YjExNGNkMjY1OWI2YjFmNWMxOWZhMDlk
        YTE2MTRlMGQxNTViMDI3OTg0ZDZjNjFhMWYyN2M1MDdiZGVhMzMxN2ExZWJjMjZhMGQxMT
        hmOWZmNDRkMmZmZjc0Y2JiZTQ0MTQyMTk4ZTQ5MmQ2YWZlZDA0OGVmYWIzZTQxMTI4MTYx
        NzY2NGI1ZjgzY2Y1ODU2MjJlNDE0NDg4Y2MyMmQ2YTFjNWE5ZTBjYTA4OWMyYzZlODMyMT
        E5ZjU3MzMxOTBmZjZiYjBlOTI5YzQzOTFlZTQxMjk0OTBkZTZiZTc3ZTQyZmQ5ZTg5MjNj
        YTYwMjZhNzgxNTQyYjQ0ZDZkNjFmNzE4ZDQxNGZiZGY5MjcxM2FiYjE1MDhkMTBjOGZjMD
        hlNDBhMmVhZGJlYjA4MTE2NzRkODNhYjBjMjVkODRlZmU2MjhkYzc2MGIzNTc5OTg5YzRm
        NzQ0ZjUyNGY5MDE2OTdiYTMzNDAzZjE0MDM1OWEzYzY4OGY1ZDI1NjdhNjgyNGNjMzBmMj
        c5YQ==
